<?php
//tags
require_once('./v1.4/Etiquetas/Base.php');
require_once('./v1.4/Etiquetas/TagInterface.php');
require_once('./v1.4/Etiquetas/helpers.php');
require_once('./v1.4/Etiquetas/A.php');
require_once('./v1.4/Etiquetas/Address.php');
require_once('./v1.4/Etiquetas/Article.php');
require_once('./v1.4/Etiquetas/B.php');
require_once('./v1.4/Etiquetas/Body.php');
require_once('./v1.4/Etiquetas/Button.php');
require_once('./v1.4/Etiquetas/Div.php');
require_once('./v1.4/Etiquetas/Doctype.php');
require_once('./v1.4/Etiquetas/Footer.php');
require_once('./v1.4/Etiquetas/H1.php');
require_once('./v1.4/Etiquetas/H2.php');
require_once('./v1.4/Etiquetas/H3.php');
require_once('./v1.4/Etiquetas/H4.php');
require_once('./v1.4/Etiquetas/H5.php');
require_once('./v1.4/Etiquetas/H6.php');
require_once('./v1.4/Etiquetas/Head.php');
require_once('./v1.4/Etiquetas/Header.php');
require_once('./v1.4/Etiquetas/Html.php');
require_once('./v1.4/Etiquetas/Img.php');
require_once('./v1.4/Etiquetas/Li.php');
require_once('./v1.4/Etiquetas/Link.php');
require_once('./v1.4/Etiquetas/Main.php');
require_once('./v1.4/Etiquetas/Meta.php');
require_once('./v1.4/Etiquetas/Ol.php');
require_once('./v1.4/Etiquetas/P.php');
require_once('./v1.4/Etiquetas/Script.php');
require_once('./v1.4/Etiquetas/Section.php');
require_once('./v1.4/Etiquetas/Span.php');
require_once('./v1.4/Etiquetas/Style.php');
require_once('./v1.4/Etiquetas/Table.php');
require_once('./v1.4/Etiquetas/Tbody.php');
require_once('./v1.4/Etiquetas/Td.php');
require_once('./v1.4/Etiquetas/Tfoot.php');
require_once('./v1.4/Etiquetas/Th.php');
require_once('./v1.4/Etiquetas/Thead.php');
require_once('./v1.4/Etiquetas/Title.php');
require_once('./v1.4/Etiquetas/Tr.php');
require_once('./v1.4/Etiquetas/Ul.php');
//mysql
require_once('./v1.4/Etiquetas/DataBase.php');
//javascript
require_once('./v1.4/Etiquetas/JsFuncMaker.php');
//css
require_once('./v1.4/Etiquetas/MQuerie.php');
require_once('./v1.4/Etiquetas/Selector.php');
require_once('./v1.4/Etiquetas/Variables.php');
require_once('./v1.4/Etiquetas/Sp2.php');